language: bash
services: docker

env:
  - VERSION=7.4 VARIANT=cli/buster/debug DISTRIBUTION=stretch
  - VERSION=7.4 VARIANT=cli/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.4 VARIANT=apache/buster/debug DISTRIBUTION=stretch
  - VERSION=7.4 VARIANT=apache/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.4 VARIANT=fpm/buster/debug DISTRIBUTION=stretch
  - VERSION=7.4 VARIANT=fpm/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=cli/buster/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=cli/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=cli/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=cli/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=apache/buster/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=apache/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=apache/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=apache/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=fpm/buster/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=fpm/buster/no-debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=fpm/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.3 VARIANT=fpm/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=cli/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=cli/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=apache/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=apache/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=fpm/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.2 VARIANT=fpm/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=cli/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=cli/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=apache/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=apache/stretch/no-debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=fpm/stretch/debug DISTRIBUTION=stretch
  - VERSION=7.1 VARIANT=fpm/stretch/no-debug DISTRIBUTION=stretch

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="php:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_script:
  - docker images
