name: Docker BUILD

on:
    workflow_dispatch:
    schedule:
        - cron: '30 2 * * *' # run a build at least once a day to keep the images up to date
    push:
        branches:
            - main

env:
    IMAGE_NAME: pimcore/pimcore

jobs:
    build-php:
        name: "Build PHP images"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.4, '8.0', '8.1']
                variant: [cli, fpm]
                distro: [bullseye, buster]
                debug: [debug, no-debug]
                exclude:
                    -   php: 7.4
                        distro: bullseye
                    -   php: '8.0'
                        distro: buster
                    -   php: '8.1'
                        distro: buster

        steps:
            -   uses: actions/checkout@v2

            -   name: run update script
                run: |
                    ./update.sh

            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Build image
                run: |
                    DOCKERFILE="build/php/${{ matrix.php }}/${{ matrix.variant }}/${{ matrix.distro }}/${{ matrix.debug }}"

                    ls -la $DOCKERFILE

                    cd $DOCKERFILE

                    ls -la .

                    docker build . -t image

            -   name: Push image
                run: |
                    IMAGE_ID=$IMAGE_NAME

                    DOCKERFILE="build/php/${{ matrix.php }}/${{ matrix.variant }}/${{ matrix.distro }}/${{ matrix.debug }}"
                    DOCKER_TAG="PHP${{ matrix.php }}-${{ matrix.variant }}"

                    cd $DOCKERFILE


                    if [ "${{ matrix.debug }}" == "debug" ]; then
                          DOCKER_TAG="$DOCKER_TAG-debug"
                    fi

                    echo "Tag $DOCKER_TAG"

                    docker tag image $IMAGE_ID:$DOCKER_TAG
                    docker push $IMAGE_ID:$DOCKER_TAG

    build-supervisor:
        name: "Build supervisord image"
        needs: build-php
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.0', '8.1' ]
        steps:
            - uses: actions/checkout@v2

            - name: Login to DockerHub Registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Build image
              run: |
                  BUILD_DIR="build/supervisor/${{ matrix.php }}"
                  mkdir -p $BUILD_DIR
                  cp supervisord/Dockerfile.template "$BUILD_DIR/Dockerfile"
                  cp supervisord/supervisord.conf "$BUILD_DIR/"

                  cd $BUILD_DIR

                  sed -ri -e 's!%%PHP_TAG%%!'${{ matrix.php }}'!' Dockerfile

                  cat Dockerfile

                  docker build . -t image

            - name: Push image
              run: |
                  IMAGE_ID=$IMAGE_NAME

                  docker tag image $IMAGE_ID:PHP${{ matrix.php }}-supervisord
                  docker push $IMAGE_ID:PHP${{ matrix.php }}-supervisord