name: Docker BUILD

on:
    workflow_dispatch:
    schedule:
        -   cron: '30 2 * * *' # run a build at least once a day to keep the images up to date
    push:

env:
    IMAGE_NAME: pimcore/pimcore

jobs:
    build-php:
        name: "Build PHP images"
        runs-on: ubuntu-latest
        if: github.repository == 'pimcore/docker'
        strategy:
            matrix:
                php: [ '8.0', '8.1' ]
                distro: [ bullseye ]
                target: [ fpm, debug, supervisord ]

        steps:
            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
                with:
                    platforms: 'amd64,arm64'

            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true

            -   name: Build and (push image if main branch)
                run: |
                    set -x;
                       
                    DOCKER_TAG="PHP${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}"

                    echo "Tag $DOCKER_TAG"

                    DOCKER_HUB_PUSH="false";
                    if [ "${{ github.ref_name }}" == "main" ]; then
                        DOCKER_HUB_PUSH="true"
                    fi

                    docker buildx build \
                      --target=pimcore_php_${{ matrix.target }} \
                      --build-arg PHP_VERSION="${{ matrix.php }}"  \
                      --build-arg DEBIAN_VERSION="${{ matrix.distro }}"  \
                      --output "type=image,push=$DOCKER_HUB_PUSH" \
                      --platform linux/amd64,linux/arm64 \
                      --tag $IMAGE_NAME:$DOCKER_TAG .

            -   name: Inspect image
                run: |
                    DOCKER_TAG="PHP${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}"
                    
                    docker buildx imagetools inspect $IMAGE_NAME:$DOCKER_TAG
