name: Docker BUILD

on:
    workflow_dispatch:
    schedule:
        -   cron: '30 2 * * *' # run a build at least once a day to keep the images up to date
    push:

env:
    IMAGE_NAME: pimcore/pimcore

jobs:
    build-php:
        name: "Build PHP images"
        runs-on: ubuntu-latest
        if: github.repository == 'pimcore/docker'
        strategy:
            matrix:
                php: [ '8.0', '8.1' ]
                distro: [ bullseye ]
                target: [ fpm, debug, supervisord ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Set Release Name
                id: vars
                run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}-

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
                with:
                    platforms: 'amd64,arm64'

            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true

            -   name: Build and (push image if main branch)
                env:
                    RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
                run: |
                    set -x;
                    
                    RELEASE_VERSION="${{ github.ref_name }}"
                    DOCKER_HUB_PUSH="false"
                    
                    if [ ${{ github.ref_name }} == "main" ]; then
                        RELEASE_VERSION="latest"
                        DOCKER_HUB_PUSH="true"
                    fi
                       
                    DOCKER_TAG="PHP${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}-$RELEASE_VERSION"

                    echo "Tag $DOCKER_TAG"

                    docker buildx build \
                      --target=pimcore_php_${{ matrix.target }} \
                      --build-arg PHP_VERSION="${{ matrix.php }}"  \
                      --build-arg DEBIAN_VERSION="${{ matrix.distro }}"  \
                      --output "type=image,push=$DOCKER_HUB_PUSH" \
                      --platform linux/amd64,linux/arm64 \
                      --cache-from "type=local,src=/tmp/.buildx-cache" \
                      --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
                      --tag $IMAGE_NAME:$DOCKER_TAG .
                    
                    docker buildx imagetools inspect $IMAGE_NAME:$DOCKER_TAG

            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

                    
