name: Docker RELEASE

on:
    push:
        tags:
            - 'v*.*'
env:
    IMAGE_NAME: pimcore/pimcore

jobs:
    build-php:
        name: "Build PHP images"
        runs-on: ubuntu-latest
        if: github.repository == 'pimcore/docker'
        strategy:
            matrix:
                php: [ '8.0', '8.1' ]
                distro: [ bullseye ]
                target: [ fpm, debug, supervisord ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Login to DockerHub Registry
                run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            -   name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}-

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
                with:
                    platforms: 'amd64,arm64'

            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v2
                with:
                    install: true

            -   name: Build and (push image if main branch)
                run: |
                    set -x;

                    DOCKER_TAG="PHP${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.target }}-${{ github.ref_name }}"

                    echo "Tag $DOCKER_TAG"

                    docker buildx build \
                      --target=pimcore_php_${{ matrix.target }} \
                      --build-arg PHP_VERSION="${{ matrix.php }}"  \
                      --build-arg DEBIAN_VERSION="${{ matrix.distro }}"  \
                      --output "type=image,push=false" \
                      --platform linux/amd64,linux/arm64 \
                      --cache-from "type=local,src=/tmp/.buildx-cache" \
                      --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
                      --tag $IMAGE_NAME:$DOCKER_TAG .
                    
                    docker buildx imagetools inspect $IMAGE_NAME:$DOCKER_TAG

            -   name: Move cache
                run: |
                    rm -rf /tmp/.buildx-cache
                    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

                    
